

class RichuiConfig {

  static Map renderers = [feedRenderer: "de.andreasschmitt.richui.taglib.renderer.FeedRenderer",
                          fontRenderer: "de.andreasschmitt.richui.taglib.renderer.FontRenderer",
                          tagCloudRenderer: "de.andreasschmitt.richui.taglib.renderer.TagCloudRenderer",
                          autoCompleteRenderer: "de.andreasschmitt.richui.taglib.renderer.AutoCompleteRenderer",
                          timelineRenderer: "de.andreasschmitt.richui.taglib.renderer.TimelineRenderer",
                          mapRenderer: "de.andreasschmitt.richui.taglib.renderer.GoogleMapsRenderer",
                          googleMapsRenderer: "de.andreasschmitt.richui.taglib.renderer.GoogleMapsRenderer",
                          yahooMapsRenderer: "de.andreasschmitt.richui.taglib.renderer.YahooMapsRenderer",
                          microsoftVirtualEarthRenderer: "de.andreasschmitt.richui.taglib.renderer.MicrosoftVirtualEarthRenderer",
                          ratingRenderer: "de.andreasschmitt.richui.taglib.renderer.RatingRenderer",
                          tooltipRenderer: "de.andreasschmitt.richui.taglib.renderer.TooltipRenderer",
                          dateChooserRenderer: "de.andreasschmitt.richui.taglib.renderer.DateChooserRenderer",
                          treeViewRenderer: "de.andreasschmitt.richui.taglib.renderer.TreeViewRenderer",
                          checkedTreeViewRenderer: "de.andreasschmitt.richui.taglib.renderer.CheckedTreeViewRenderer",
                          tabViewRenderer: "de.andreasschmitt.richui.taglib.renderer.TabViewRenderer",
                          tabLabelsRenderer: "de.andreasschmitt.richui.taglib.renderer.TabLabelsRenderer",
                          tabLabelRenderer: "de.andreasschmitt.richui.taglib.renderer.TabLabelRenderer",
                          tabContentsRenderer: "de.andreasschmitt.richui.taglib.renderer.TabContentsRenderer",
                          tabContentRenderer: "de.andreasschmitt.richui.taglib.renderer.TabContentRenderer",
                          progressBarRenderer: "de.andreasschmitt.richui.taglib.renderer.ProgressBarRenderer",
                          reflectionImageRenderer: "de.andreasschmitt.richui.taglib.renderer.ReflectionImageRenderer",
                          calendarDayViewRenderer: "de.andreasschmitt.richui.taglib.renderer.CalendarDayViewRenderer",
                          calendarMonthViewRenderer: "de.andreasschmitt.richui.taglib.renderer.CalendarMonthViewRenderer",
                          calendarWeekViewRenderer: "de.andreasschmitt.richui.taglib.renderer.CalendarWeekViewRenderer",
                          richTextEditorRenderer: "de.andreasschmitt.richui.taglib.renderer.RichTextEditorRenderer",
                          carouselRenderer: "de.andreasschmitt.richui.taglib.renderer.CarouselRenderer",
                          carouselItemRenderer: "de.andreasschmitt.richui.taglib.renderer.CarouselItemRenderer",
                          portletRenderer: "de.andreasschmitt.richui.taglib.renderer.PortletRenderer",
                          portletViewRenderer: "de.andreasschmitt.richui.taglib.renderer.PortletViewRenderer",
                          flowRenderer: "de.andreasschmitt.richui.taglib.renderer.FlowRenderer",
                          //flowRenderer: "de.andreasschmitt.richui.taglib.renderer.RunwayFlowRenderer",
                          accordionRenderer: "de.andreasschmitt.richui.taglib.renderer.AccordionRenderer",
                          accordionItemRenderer: "de.andreasschmitt.richui.taglib.renderer.AccordionItemRenderer",
                          sliderRenderer: "de.andreasschmitt.richui.taglib.renderer.GlowSliderRenderer",
                          lightBoxRenderer: "de.andreasschmitt.richui.taglib.renderer.LightBoxRenderer"]
  
}